[package]
name = "acai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
atty = "0.2.14"
clap = { version = "4.5.60", features = ["derive"] }
dashmap = "6.1.0"
dirs = "6.0"
glob = "0.3.3"
handlebars = "6.4.0"
ignore = "0.4"
log = "0.4.29"
log4rs = "1.4.0"
once_cell = "1.21.3"
regex = "1.12.3"
reqwest = { version = "0.13.2", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
similar = "2.7.0"
termtree = "1.0.0"
text-splitter = "0.29"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
